# Generated by Django 5.2.16 on 2026-08-06 07:31

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0011_course_offering_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('passing_grade', models.DecimalField(decimal_places=2, default=Decimal('10.50'), max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('10.50')), django.core.validators.MaxValueValidator(Decimal('10.50'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='evaluation_scheme', to='academics.courseoffering')),
            ],
            options={
                'verbose_name': 'esquema de evaluación',
                'verbose_name_plural': 'esquemas de evaluación',
                'ordering': ['-course_offering__academic_period__year', 'course_offering__academic_period__term', 'course_offering__course__code'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('component_type', models.CharField(choices=[('EXAM_1', 'Examen 1'), ('EXAM_2', 'Examen 2'), ('SUBSTITUTE', 'Sustitutorio'), ('OTHER', 'Otro componente')], default='OTHER', max_length=10)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='grading.evaluationscheme')),
            ],
            options={
                'verbose_name': 'componente de evaluación',
                'verbose_name_plural': 'componentes de evaluación',
                'ordering': ['scheme_id', 'order', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationscheme',
            constraint=models.CheckConstraint(condition=models.Q(('passing_grade', Decimal('10.50'))), name='evaluation_scheme_passing_grade_exact'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcomponent',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('scheme'), name='unique_evaluation_component_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('component_type', 'OTHER'), _negated=True), fields=('scheme', 'component_type'), name='unique_special_component_type_per_scheme'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcomponent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('component_type', 'SUBSTITUTE'), ('weight', 0)), models.Q(('weight__gt', 0), ('weight__lte', 100), models.Q(('component_type', 'SUBSTITUTE'), _negated=True)), _connector='OR'), name='evaluation_component_weight_by_type'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='evaluation_component_name_not_empty'),
        ),
    ]
