# Generated by Django 5.2.17 on 2026-08-10 22:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Periodo Académico',
                'verbose_name_plural': 'Periodos Académicos',
                'db_table': 'curricula_academic_term',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'curricula_instructor',
            },
        ),
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('min_elective_branches_to_complete', models.PositiveSmallIntegerField(default=2, help_text='Minimum number of distinct elective branches the student must complete (have at least one passed course in) to graduate.')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_plans', to='institution.professionalschool')),
            ],
            options={
                'verbose_name': 'Plan Curricular',
                'verbose_name_plural': 'Planes Curriculares',
                'db_table': 'curricula_curriculum_plan',
            },
        ),
        migrations.CreateModel(
            name='ElectiveBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_branches', to='curricula.curriculumplan')),
            ],
            options={
                'verbose_name': 'Rama Electiva',
                'verbose_name_plural': 'Ramas Electivas',
                'db_table': 'curricula_elective_branch',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('credits', models.DecimalField(decimal_places=1, max_digits=4)),
                ('theory_hours', models.PositiveSmallIntegerField(default=0)),
                ('practice_hours', models.PositiveSmallIntegerField(default=0)),
                ('seminar_hours', models.PositiveSmallIntegerField(default=0)),
                ('theory_practice_hours', models.PositiveSmallIntegerField(default=0)),
                ('lab_hours', models.PositiveSmallIntegerField(default=0)),
                ('cycle', models.PositiveSmallIntegerField(help_text='1-10, suggested cycle in the plan.')),
                ('course_type', models.CharField(choices=[('mandatory', 'Obligatorio'), ('elective', 'Electivo')], max_length=20)),
                ('academic_area', models.CharField(choices=[('general_education', 'Formación general'), ('specialty', 'Especialidad'), ('elective', 'Electivo')], max_length=30)),
                ('min_credits_required', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curricula.curriculumplan')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='curricula.electivebranch')),
            ],
            options={
                'verbose_name': 'Asignatura',
                'verbose_name_plural': 'Asignaturas',
                'db_table': 'curricula_course',
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='curricula.course')),
                ('required_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='curricula.course')),
            ],
            options={
                'verbose_name': 'Prerrequisito',
                'verbose_name_plural': 'Prerrequisitos',
                'db_table': 'curricula_prerequisite',
            },
        ),
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('competencies', models.TextField(blank=True)),
                ('thematic_content', models.TextField(blank=True)),
                ('methodology', models.TextField(blank=True)),
                ('evaluation_criteria', models.TextField(blank=True)),
                ('weekly_plan', models.TextField(blank=True)),
                ('bibliography', models.TextField(blank=True)),
                ('resources', models.TextField(blank=True)),
                ('lab_practice_info', models.TextField(blank=True)),
                ('institutional_references', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='curricula.academicterm')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabi', to='curricula.course')),
                ('instructors', models.ManyToManyField(related_name='syllabi', to='curricula.instructor')),
            ],
            options={
                'verbose_name': 'Sílabo',
                'verbose_name_plural': 'Sílabos',
                'db_table': 'curricula_syllabus',
            },
        ),
        migrations.CreateModel(
            name='EvaluationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('order', models.PositiveSmallIntegerField()),
                ('syllabus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_components', to='curricula.syllabus')),
            ],
            options={
                'verbose_name': 'Componente de Evaluación',
                'verbose_name_plural': 'Componentes de Evaluación',
                'db_table': 'curricula_evaluation_component',
                'ordering': ['syllabus', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='curriculumplan',
            constraint=models.UniqueConstraint(fields=('school', 'year'), name='unique_plan_year_per_school'),
        ),
        migrations.AddConstraint(
            model_name='electivebranch',
            constraint=models.UniqueConstraint(fields=('curriculum_plan', 'name'), name='unique_branch_name_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('curriculum_plan', 'code'), name='unique_course_code_per_plan'),
        ),
        migrations.AddConstraint(
            model_name='prerequisite',
            constraint=models.UniqueConstraint(fields=('course', 'required_course'), name='unique_prerequisite_pair'),
        ),
        migrations.AddConstraint(
            model_name='syllabus',
            constraint=models.UniqueConstraint(fields=('course', 'academic_term'), name='unique_syllabus_per_term'),
        ),
        migrations.AddConstraint(
            model_name='evaluationcomponent',
            constraint=models.UniqueConstraint(fields=('syllabus', 'order'), name='unique_component_order_per_syllabus'),
        ),
    ]
