# Generated by Django 5.2.17 on 2026-08-16 22:56

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(help_text='Año del plan de estudios')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum_plans', to='institution.professionalschool')),
            ],
            options={
                'db_table': 'curricula_curriculum_plan',
                'ordering': ['-year'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ElectiveBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elective_branches', to='curricula.curriculumplan')),
            ],
            options={
                'db_table': 'curricula_elective_branch',
                'ordering': ['name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Ej: 1701102 o 2504252', max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('credits', models.DecimalField(decimal_places=2, max_digits=4)),
                ('theory_hours', models.PositiveIntegerField(default=0, verbose_name='Horas Teóricas (TEOR)')),
                ('seminar_hours', models.PositiveIntegerField(default=0, verbose_name='Horas Seminario (SEMI)')),
                ('theory_practice_hours', models.PositiveIntegerField(default=0, verbose_name='Horas Teórico-Prácticas (T.PR)')),
                ('practice_hours', models.PositiveIntegerField(default=0, verbose_name='Horas Prácticas (PRAC)')),
                ('lab_hours', models.PositiveIntegerField(default=0, verbose_name='Horas Laboratorio (LAB)')),
                ('cycle', models.PositiveIntegerField(help_text='Ciclo del 1 al 10')),
                ('course_type', models.CharField(choices=[('mandatory', 'Obligatorio'), ('elective', 'Electivo')], default='mandatory', max_length=20)),
                ('academic_area', models.CharField(choices=[('A', 'Formación Básica'), ('B', 'Formación Especializada'), ('C', 'Formación Profesional y Otros'), ('D', 'Est.Gen.: Capacidades de Aprendizaje'), ('E', 'Est.Gen.: Form.Humanist.Ident. y Ciudadania'), ('F', 'Estudios Específicos'), ('G', 'Estudios de Especialidad')], help_text='Componente curricular (A, B, C, D, E, F, G)', max_length=2)),
                ('min_credits_required', models.PositiveIntegerField(blank=True, help_text='Créditos acumulados requeridos (ej. 190 para Proyecto Integrador)', null=True)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='curricula.curriculumplan')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='curricula.electivebranch')),
            ],
            options={
                'db_table': 'curricula_course',
                'ordering': ['cycle', 'name'],
                'constraints': [models.UniqueConstraint(fields=('curriculum_plan', 'code'), name='unique_course_code_per_plan')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
