# Generated by Django 5.2.17 on 2026-08-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_alter_academicterm_managers_alter_course_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicterm',
            options={'ordering': ['-created_at'], 'verbose_name': 'Periodo Académico', 'verbose_name_plural': 'Periodos Académicos'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Asignatura', 'verbose_name_plural': 'Asignaturas'},
        ),
        migrations.AlterModelOptions(
            name='curriculumplan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plan Curricular', 'verbose_name_plural': 'Planes Curriculares'},
        ),
        migrations.AlterModelOptions(
            name='electivebranch',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rama Electiva', 'verbose_name_plural': 'Ramas Electivas'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Docente', 'verbose_name_plural': 'Docentes'},
        ),
        migrations.AlterModelOptions(
            name='prerequisite',
            options={'ordering': ['-created_at'], 'verbose_name': 'Prerrequisito', 'verbose_name_plural': 'Prerrequisitos'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'ordering': ['-created_at'], 'verbose_name': 'Sílabo', 'verbose_name_plural': 'Sílabos'},
        ),
    ]
