# Generated by Django 5.2.17 on 2026-08-18 01:11

from django.db import migrations


def populate_epis_plans(apps, schema_editor):
    ProfessionalSchool = apps.get_model('institution', 'ProfessionalSchool')
    CurriculumPlan = apps.get_model('curricula', 'CurriculumPlan')

    try:
        epis_school = ProfessionalSchool._default_manager.get(acronym='EPIS')

        plans_to_create = [
            {
                "name": "Plan de Estudios 2017",
                "year": 2017
            },
            {
                "name": "Plan de Estudios 2025",
                "year": 2025
            }
        ]

        for plan in plans_to_create:
            CurriculumPlan._default_manager.update_or_create(
                school=epis_school,
                year=plan["year"],
                defaults={
                    "name": plan["name"]
                }
            )

    except ProfessionalSchool.DoesNotExist:
        print("Error: No se encontró la Escuela Profesional con acrónimo 'EPIS'.")

def rollback_epis_plans(apps, schema_editor):
    CurriculumPlan = apps.get_model('curricula', 'CurriculumPlan')
    CurriculumPlan._default_manager.filter(school__acronym='EPIS').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0002_prerequisite'),
        ('institution', '0003_populate_professional_schools'),
    ]

    operations = [
        migrations.RunPython(populate_epis_plans, reverse_code=rollback_epis_plans),
    ]
