# Generated by Django 5.2.17 on 2026-08-18 04:00

from django.db import migrations


def populate_all_curriculum_plans(apps, schema_editor):
    ProfessionalSchool = apps.get_model('institution', 'ProfessionalSchool')
    CurriculumPlan = apps.get_model('curricula', 'CurriculumPlan')

    all_schools = ProfessionalSchool._default_manager.all()

    plans_to_create = [
        {"name": "Plan de Estudios 2017", "year": 2017},
        {"name": "Plan de Estudios 2025", "year": 2025}
    ]

    for school in all_schools:
        for plan in plans_to_create:
            CurriculumPlan._default_manager.update_or_create(
                school=school,
                year=plan["year"],
                defaults={
                    "name": plan["name"]
                }
            )

def rollback_all_curriculum_plans(apps, schema_editor):
    CurriculumPlan = apps.get_model('curricula', 'CurriculumPlan')
    CurriculumPlan._default_manager.filter(year__in=[2017, 2025]).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('curricula', '0003_populate_epis_curriculum_plans'),
    ]

    operations = [
        migrations.RunPython(populate_all_curriculum_plans, reverse_code=rollback_all_curriculum_plans),
    ]
