# Generated by Django 5.2.17 on 2026-08-12 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offerings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offering',
            options={'ordering': ['-created_at'], 'verbose_name': 'Oferta', 'verbose_name_plural': 'Ofertas'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['offering', 'section_type', 'number'], 'verbose_name': 'Grupo', 'verbose_name_plural': 'Grupos'},
        ),
    ]
