# Generated by Django 5.2.17 on 2026-08-12 22:05

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_membershiprequest_managers_and_more'),
        ('curricula', '0002_alter_academicterm_managers_alter_course_managers_and_more'),
        ('offerings', '0002_alter_offering_options_alter_section_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('in_progress', 'En curso'), ('passed', 'Aprobado'), ('failed', 'Desaprobado'), ('withdrawn', 'Retirado')], default='in_progress', max_length=15)),
                ('lab_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_enrollments', to='offerings.section')),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='offerings.offering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to='accounts.studentprofile')),
                ('theory_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theory_enrollments', to='offerings.section')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'academic_records_course_enrollment',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('20'))])),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academic_records.courseenrollment')),
                ('evaluation_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='curricula.evaluationcomponent')),
            ],
            options={
                'verbose_name': 'Nota',
                'verbose_name_plural': 'Notas',
                'db_table': 'academic_records_grade',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('student', 'offering'), name='unique_enrollment_per_offering'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('enrollment', 'evaluation_component'), name='unique_grade_per_component'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 20)), name='score_between_0_and_20'),
        ),
    ]
