# Generated by Django 5.2.17 on 2026-08-12 22:05

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_membershiprequest_managers_and_more'),
        ('curricula', '0002_alter_academicterm_managers_alter_course_managers_and_more'),
        ('offerings', '0002_alter_offering_options_alter_section_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('rank', models.PositiveSmallIntegerField(help_text='1 = best, up to 4.')),
                ('is_favorite', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alternativa de Horario',
                'verbose_name_plural': 'Alternativas de Horario',
                'db_table': 'schedules_schedule_alternative',
                'ordering': ['rank'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='PublicShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('include_personal_info', models.BooleanField(default=False)),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='schedules.schedulealternative')),
            ],
            options={
                'verbose_name': 'Enlace Público de Horario',
                'verbose_name_plural': 'Enlaces Públicos de Horario',
                'db_table': 'schedules_public_share_link',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('academic_term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_simulations', to='curricula.academicterm')),
                ('offerings', models.ManyToManyField(related_name='schedule_simulations', to='offerings.offering')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_simulations', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Simulación de Horario',
                'verbose_name_plural': 'Simulaciones de Horario',
                'db_table': 'schedules_schedule_simulation',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='schedulealternative',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='schedules.schedulesimulation'),
        ),
        migrations.CreateModel(
            name='ScheduleAlternativeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schedules.schedulealternative')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_alternatives', to='offerings.section')),
            ],
            options={
                'db_table': 'schedules_schedule_alternative_section',
                'constraints': [models.UniqueConstraint(fields=('alternative', 'section'), name='unique_section_per_alternative')],
            },
        ),
        migrations.AddConstraint(
            model_name='schedulealternative',
            constraint=models.UniqueConstraint(fields=('simulation', 'rank'), name='unique_rank_per_simulation'),
        ),
    ]
