# Generated by Django 5.2.17 on 2026-08-10 22:48

import apps.accounts.managers
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('curricula', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('google_sub', models.CharField(blank=True, help_text="The Google account's 'sub' identifier. Empty for accounts created only for the Django admin.", max_length=255, null=True, unique=True)),
                ('is_platform_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'accounts_user',
            },
            managers=[
                ('objects', apps.accounts.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cui', models.CharField(help_text='Código Único de Identificación del estudiante.', max_length=20, unique=True, verbose_name='CUI')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de estudiante',
                'verbose_name_plural': 'Perfiles de estudiante',
                'db_table': 'accounts_student_profile',
            },
        ),
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('initial_request', 'Solicitud inicial'), ('add_second_program', 'Agregar segunda carrera'), ('error_correction', 'Corrección por error')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=15)),
                ('evidence_url', models.URLField(blank=True)),
                ('resolution_comment', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_requests', to='curricula.curriculumplan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membership_requests_resolved', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='membership_requests', to='institution.professionalschool')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Solicitud de membresía',
                'verbose_name_plural': 'Solicitudes de membresía',
                'db_table': 'accounts_membership_request',
            },
        ),
        migrations.CreateModel(
            name='SchoolDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_assigned', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='institution.professionalschool')),
            ],
            options={
                'verbose_name': 'Delegación de escuela',
                'verbose_name_plural': 'Delegaciones de escuela',
                'db_table': 'accounts_school_delegation',
                'constraints': [models.UniqueConstraint(fields=('delegate', 'school'), name='unique_delegation_per_school')],
            },
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField()),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='curricula.curriculumplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='institution.professionalschool')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_verified', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.studentprofile')),
            ],
            options={
                'verbose_name': 'Membresía de escuela',
                'verbose_name_plural': 'Membresías de escuela',
                'db_table': 'accounts_school_membership',
                'constraints': [models.UniqueConstraint(fields=('student', 'school'), name='unique_membership_per_school')],
            },
        ),
    ]
