# Generated by Django 5.2.17 on 2026-08-16 23:40

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('curricula', '0001_initial'),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=15)),
                ('resolution_comment', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curricula.curriculumplan')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='institution.professionalschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de membresía',
                'verbose_name_plural': 'Solicitudes de membresía',
                'db_table': 'accounts_membership_request',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(choices=[('cui_correction', 'Corrección de CUI'), ('technical_issue', 'Problema Técnico'), ('other', 'Otro')], max_length=30)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('resolved', 'Resuelto'), ('rejected', 'Rechazado')], default='pending', max_length=15)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_resolved', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, help_text='Opcional. Ayuda a enrutar el ticket al delegado correcto.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.professionalschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_support_ticket',
                'ordering': ['-created_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDelegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegations_assigned', to=settings.AUTH_USER_MODEL)),
                ('delegate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='institution.professionalschool')),
            ],
            options={
                'verbose_name': 'Delegación de escuela',
                'verbose_name_plural': 'Delegaciones de escuela',
                'db_table': 'accounts_school_delegation',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('delegate', 'school'), name='unique_delegation_per_school')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='curricula.curriculumplan')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='institution.professionalschool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membresía de escuela',
                'verbose_name_plural': 'Membresías de escuela',
                'db_table': 'accounts_school_membership',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'school'), name='unique_membership_per_school')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
