# Generated by Django 5.2.16 on 2026-08-03 01:56

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[apps.accounts.validators.validate_institutional_email], verbose_name='correo electrónico'),
        ),
    ]
