# Generated by Django 5.2.17 on 2026-08-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_membershiprequest_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiprequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de membresía', 'verbose_name_plural': 'Solicitudes de membresía'},
        ),
        migrations.AlterModelOptions(
            name='schooldelegation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Delegación de escuela', 'verbose_name_plural': 'Delegaciones de escuela'},
        ),
        migrations.AlterModelOptions(
            name='schoolmembership',
            options={'ordering': ['-created_at'], 'verbose_name': 'Membresía de escuela', 'verbose_name_plural': 'Membresías de escuela'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Perfil de estudiante', 'verbose_name_plural': 'Perfiles de estudiante'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
