# Generated by Django 5.2.16 on 2026-08-06 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_add_curriculum_course'),
        ('accounts', '0007_assign_existing_google_users_student_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='academic_admin_assignments', to='academics.professionalschool')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_admin_assignment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asignación de administrador académico',
                'verbose_name_plural': 'asignaciones de administradores académicos',
                'ordering': ['user__email'],
            },
        ),
    ]
