# Generated by Django 5.2.16 on 2026-08-03 23:29

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_schools', to='academics.faculty')),
            ],
            options={
                'verbose_name': 'escuela profesional',
                'verbose_name_plural': 'escuelas profesionales',
                'ordering': ['faculty__name', 'name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('faculty'), name='unique_school_name_per_faculty_ci'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='professional_school_name_not_empty')],
            },
        ),
    ]
