# Generated by Django 5.2.16 on 2026-08-03 23:34

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_add_professional_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional_school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_plans', to='academics.professionalschool')),
            ],
            options={
                'verbose_name': 'plan de estudios',
                'verbose_name_plural': 'planes de estudios',
                'ordering': ['professional_school__name', 'code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('code'), models.F('professional_school'), name='unique_plan_code_per_school_ci'), models.CheckConstraint(condition=models.Q(('code', ''), _negated=True), name='curriculum_plan_code_not_empty'), models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='curriculum_plan_name_not_empty')],
            },
        ),
    ]
