# Generated by Django 5.2.16 on 2026-08-03 23:51

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_add_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cycle', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('credits', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_entries', to='academics.course')),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='curriculum_courses', to='academics.curriculumplan')),
            ],
            options={
                'verbose_name': 'asignatura del plan',
                'verbose_name_plural': 'asignaturas del plan',
                'ordering': ['curriculum_plan_id', 'cycle', 'course__code'],
                'constraints': [models.UniqueConstraint(fields=('curriculum_plan', 'course'), name='unique_course_per_curriculum_plan'), models.CheckConstraint(condition=models.Q(('cycle__gte', 1)), name='curriculum_course_cycle_gte_1'), models.CheckConstraint(condition=models.Q(('credits__gte', 0)), name='curriculum_course_credits_gte_0')],
            },
        ),
    ]
