# Generated by Django 5.2.16 on 2026-08-06 05:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_add_curriculum_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('term', models.CharField(choices=[('A', 'Primer semestre'), ('B', 'Segundo semestre')], max_length=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'periodo académico',
                'verbose_name_plural': 'periodos académicos',
                'ordering': ['-year', 'term'],
                'constraints': [models.UniqueConstraint(fields=('year', 'term'), name='unique_academic_period_year_term')],
            },
        ),
    ]
