# Generated by Django 5.2.16 on 2026-08-06 05:54

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_academicperiod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('group_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='course_offerings', to='academics.academicperiod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='academics.course')),
            ],
            options={
                'verbose_name': 'oferta de asignatura',
                'verbose_name_plural': 'ofertas de asignaturas',
                'ordering': ['-academic_period__year', 'academic_period__term', 'course__code', 'group_code'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('group_code'), models.F('academic_period'), models.F('course'), name='unique_course_group_per_period_ci'), models.CheckConstraint(condition=models.Q(('group_code', ''), _negated=True), name='course_offering_group_code_not_empty')],
            },
        ),
    ]
