# Generated by Django 5.2.16 on 2026-08-06 07:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_courseoffering'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculumcourse',
            name='component',
            field=models.CharField(choices=[('A', 'Formación básica'), ('B', 'Formación especializada'), ('C', 'Formación profesional y otros'), ('D', 'Estudios generales: capacidades de aprendizaje'), ('E', 'Estudios generales: formación humanista, identidad y ciudadanía'), ('F', 'Estudios específicos'), ('G', 'Estudios de especialidad')], default='F', max_length=1),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='laboratory_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='practice_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='prerequisite_credits',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='seminar_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='theory_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='theory_practice_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.CheckConstraint(condition=models.Q(('laboratory_hours__gte', 0), ('practice_hours__gte', 0), ('prerequisite_credits__gte', 0), ('seminar_hours__gte', 0), ('theory_hours__gte', 0), ('theory_practice_hours__gte', 0)), name='curriculum_course_hours_and_prereq_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourse',
            constraint=models.CheckConstraint(condition=models.Q(('component__in', ('A', 'B', 'C', 'D', 'E', 'F', 'G'))), name='curriculum_course_component_valid'),
        ),
    ]
