# Generated by Django 5.2.16 on 2026-08-06 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_expand_curriculum_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumCoursePrerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_links', to='academics.curriculumcourse')),
                ('prerequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependent_links', to='academics.curriculumcourse')),
            ],
            options={
                'verbose_name': 'prerrequisito de asignatura del plan',
                'verbose_name_plural': 'prerrequisitos de asignaturas del plan',
                'ordering': ['curriculum_course_id', 'prerequisite_id'],
            },
        ),
        migrations.AddField(
            model_name='curriculumcourse',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='required_by', through='academics.CurriculumCoursePrerequisite', through_fields=('curriculum_course', 'prerequisite'), to='academics.curriculumcourse'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourseprerequisite',
            constraint=models.UniqueConstraint(fields=('curriculum_course', 'prerequisite'), name='unique_curriculum_course_prerequisite'),
        ),
        migrations.AddConstraint(
            model_name='curriculumcourseprerequisite',
            constraint=models.CheckConstraint(condition=models.Q(('curriculum_course', models.F('prerequisite')), _negated=True), name='curriculum_course_prerequisite_not_self'),
        ),
    ]
