# Generated by Django 5.2.16 on 2026-08-06 19:22

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_course_offering_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourseAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('ENROLLED', 'En curso'), ('PASSED', 'Aprobado'), ('FAILED', 'Desaprobado'), ('WITHDRAWN', 'Retirado')], default='ENROLLED', max_length=10)),
                ('final_grade', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attempts', to='academics.courseoffering')),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_attempts', to='academics.curriculumcourse')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'intento académico del estudiante',
                'verbose_name_plural': 'intentos académicos de estudiantes',
                'ordering': ['student__email', '-course_offering__academic_period__year', 'course_offering__academic_period__term', 'course_offering__course__code'],
                'constraints': [models.UniqueConstraint(fields=('student', 'course_offering'), name='unique_student_course_attempt_per_offering'), models.CheckConstraint(condition=models.Q(('final_grade__isnull', True), models.Q(('final_grade__gte', Decimal('0.00')), ('final_grade__lte', Decimal('20.00'))), _connector='OR'), name='student_course_attempt_grade_range'), models.CheckConstraint(condition=models.Q(models.Q(('final_grade__gte', Decimal('10.50')), ('status', 'PASSED')), models.Q(('final_grade__isnull', False), ('final_grade__lt', Decimal('10.50')), ('status', 'FAILED')), models.Q(('final_grade__isnull', True), ('status__in', ['ENROLLED', 'WITHDRAWN'])), _connector='OR'), name='student_course_attempt_status_grade_consistent')],
            },
        ),
    ]
