# Generated by Django 5.2.17 on 2026-08-12 02:32

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='area',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='faculty',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='professionalschool',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
