# Generated by Django 5.2.17 on 2026-08-18 01:01

from django.db import migrations

def populate_unsa_faculties(apps, schema_editor):
    Faculty = apps.get_model('institution', 'Faculty')

    faculties = [
        # --- ÁREA DE INGENIERÍAS ---
        {
            "name": "Facultad de Arquitectura y Urbanismo",
            "acronym": "FAU",
            "area": "ingenierias",
            "description": "Facultad enfocada en la formación de arquitectos y el desarrollo urbano sostenible."
        },
        {
            "name": "Facultad de Ciencias Naturales y Formales",
            "acronym": "FCNF",
            "area": "ingenierias",
            "description": "Comprende especialidades puras y aplicadas en física, química, matemáticas y estadística."
        },
        {
            "name": "Facultad de Ingeniería Civil",
            "acronym": "FIC",
            "area": "ingenierias",
            "description": "Dedicada al diseño, construcción y mantenimiento de infraestructuras estructurales."
        },
        {
            "name": "Facultad de Geología, Geofísica y Minas",
            "acronym": "FGGM",
            "area": "ingenierias",
            "description": "Especializada en ciencias de la tierra, prospección y explotación minera responsable."
        },
        {
            "name": "Facultad de Ingeniería de Procesos",
            "acronym": "FIP",
            "area": "ingenierias",
            "description": "Incluye carreras como Ingeniería Química, Ambiental, de Materiales e Industrias Alimentarias."
        },
        {
            "name": "Facultad de Ingeniería de Producción y Servicios",
            "acronym": "FIPS",
            "area": "ingenierias",
            "description": "Aloja programas clave como Ingeniería de Sistemas, Eléctrica, Electrónica, Mecánica e Industrial."
        },

        # --- ÁREA BIOMÉDICAS ---
        {
            "name": "Facultad de Agronomía",
            "acronym": "FA",
            "area": "biomedicas",
            "description": "Formación en producción agrícola sostenible y seguridad alimentaria."
        },
        {
            "name": "Facultad de Ciencias Biológicas",
            "acronym": "FCB",
            "area": "biomedicas",
            "description": "Enfocada en el estudio integral de los seres vivos y la biotecnología."
        },
        {
            "name": "Facultad de Enfermería",
            "acronym": "FE",
            "area": "biomedicas",
            "description": "Dedicada al cuidado de la salud humana, prevención de enfermedades y gestión hospitalaria."
        },
        {
            "name": "Facultad de Medicina",
            "acronym": "FM",
            "area": "biomedicas",
            "description": "Instancia insignia para la formación de médicos cirujanos y especialistas de la salud."
        },

        # --- ÁREA SOCIALES ---
        {
            "name": "Facultad de Administración",
            "acronym": "FADM",
            "area": "sociales",
            "description": "Agrupa especialidades en administración de empresas, marketing, gestión pública y de negocios."
        },
        {
            "name": "Facultad de Ciencias Contables y Financieras",
            "acronym": "FCCF",
            "area": "sociales",
            "description": "Dedicada a la contabilidad pública, auditoría y optimización financiera institucional."
        },
        {
            "name": "Facultad de Ciencias de la Educación",
            "acronym": "FCE",
            "area": "sociales",
            "description": "Formación de docentes en múltiples especialidades de los niveles inicial, primario y secundario."
        },
        {
            "name": "Facultad de Ciencias Histórico Sociales",
            "acronym": "FCHS",
            "area": "sociales",
            "description": "Incluye especialidades como Historia, Sociología, Antropología, Trabajo Social y Turismo."
        },
        {
            "name": "Facultad de Economía",
            "acronym": "FECO",
            "area": "sociales",
            "description": "Enfocada en el análisis económico, formulación de políticas públicas y modelos predictivos."
        },
        {
            "name": "Facultad de Filosofía y Humanidades",
            "acronym": "FFH",
            "area": "sociales",
            "description": "Espacio de reflexión crítica que aloja especialidades de Literatura, Filosofía y Artes."
        },
        {
            "name": "Facultad de Derecho",
            "acronym": "FD",
            "area": "sociales",
            "description": "Formación jurídica sólida orientada al litigio, asesoría legal y magistratura."
        },
        {
            "name": "Facultad de Psicología, Relaciones Industriales y Ciencias de la Comunicación",
            "acronym": "FPRICC",
            "area": "sociales",
            "description": "Agrupa el comportamiento humano individual, organizacional y la difusión mediática de la información."
        },
    ]

    for faculty_data in faculties:
        Faculty._default_manager.update_or_create(
            acronym=faculty_data["acronym"],
            defaults={
                "name": faculty_data["name"],
                "area": faculty_data["area"],
                "description": faculty_data["description"]
            }
        )

def rollback_unsa_faculties(apps, schema_editor):
    Faculty = apps.get_model('institution', 'Faculty')
    Faculty._default_manager.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_unsa_faculties, reverse_code=rollback_unsa_faculties),
    ]
