# Generated by Django 5.2.17 on 2026-08-18 01:03

from django.db import migrations

def populate_unsa_schools(apps, schema_editor):
    Faculty = apps.get_model('institution', 'Faculty')
    ProfessionalSchool = apps.get_model('institution', 'ProfessionalSchool')

    schools_by_faculty = {
        # --- INGENIERÍAS ---
        "FAU": [
            {"name": "Escuela Profesional de Arquitectura", "acronym": "EPA"}
        ],
        "FIC": [
            {"name": "Escuela Profesional de Ingeniería Civil", "acronym": "EPIC"}
        ],
        "FCNF": [
            {"name": "Escuela Profesional de Física", "acronym": "EPF"},
            {"name": "Escuela Profesional de Matemáticas", "acronym": "EPM"},
            {"name": "Escuela Profesional de Química", "acronym": "EPQ"},
            {"name": "Escuela Profesional de Estadística", "acronym": "EPE"}
        ],
        "FGGM": [
            {"name": "Escuela Profesional de Ingeniería Geológica", "acronym": "EPIG"},
            {"name": "Escuela Profesional de Ingeniería Geofísica", "acronym": "EPIGF"},
            {"name": "Escuela Profesional de Ingeniería de Minas", "acronym": "EPIM"}
        ],
        "FIP": [
            {"name": "Escuela Profesional de Ingeniería Química", "acronym": "EPIQ"},
            {"name": "Escuela Profesional de Ingeniería Ambiental", "acronym": "EPIA"},
            {"name": "Escuela Profesional de Ingeniería de Materiales", "acronym": "EPIMAT"},
            {"name": "Escuela Profesional de Ingeniería de Industrias Alimentarias", "acronym": "EPIAL"}
        ],
        "FIPS": [
            {"name": "Escuela Profesional de Ingeniería de Sistemas", "acronym": "EPIS"},
            {"name": "Escuela Profesional de Ingeniería Industrial", "acronym": "EPII"},
            {"name": "Escuela Profesional de Ingeniería Electrónica", "acronym": "EPIEL"},
            {"name": "Escuela Profesional de Ingeniería Eléctrica", "acronym": "EPIE"},
            {"name": "Escuela Profesional de Ingeniería Mecánica", "acronym": "EPIMEC"},
            {"name": "Escuela Profesional de Ingeniería de Telecomunicaciones", "acronym": "EPIT"}
        ],

        # --- BIOMÉDICAS ---
        "FA": [
            {"name": "Escuela Profesional de Agronomía", "acronym": "EPAGR"}
        ],
        "FCB": [
            {"name": "Escuela Profesional de Biología", "acronym": "EPB"},
            {"name": "Escuela Profesional de Ciencias de la Nutrición", "acronym": "EPCN"}
        ],
        "FE": [
            {"name": "Escuela Profesional de Enfermería", "acronym": "EPENF"}
        ],
        "FM": [
            {"name": "Escuela Profesional de Medicina", "acronym": "EPMED"}
        ],

        # --- SOCIALES ---
        "FADM": [
            {"name": "Escuela Profesional de Administración", "acronym": "EPADM"},
            {"name": "Escuela Profesional de Marketing", "acronym": "EPMKT"},
            {"name": "Escuela Profesional de Gestión", "acronym": "EPGES"}
        ],
        "FCCF": [
            {"name": "Escuela Profesional de Contabilidad", "acronym": "EPCONT"},
            {"name": "Escuela Profesional de Finanzas", "acronym": "EPFIN"}
        ],
        "FCE": [
            {"name": "Escuela Profesional de Educación", "acronym": "EPEDUC"}
        ],
        "FCHS": [
            {"name": "Escuela Profesional de Historia", "acronym": "EPHIS"},
            {"name": "Escuela Profesional de Sociología", "acronym": "EPSOC"},
            {"name": "Escuela Profesional de Antropología", "acronym": "EPANT"},
            {"name": "Escuela Profesional de Trabajo Social", "acronym": "EPTS"},
            {"name": "Escuela Profesional de Turismo y Hotelería", "acronym": "EPTH"}
        ],
        "FECO": [
            {"name": "Escuela Profesional de Economía", "acronym": "EPECO"}
        ],
        "FD": [
            {"name": "Escuela Profesional de Derecho", "acronym": "EPDER"}
        ],
        "FFH": [
            {"name": "Escuela Profesional de Filosofía", "acronym": "EPFIL"},
            {"name": "Escuela Profesional de Literatura y Lingüística", "acronym": "EPLL"},
            {"name": "Escuela Profesional de Artes", "acronym": "EPART"}
        ],
        "FPRICC": [
            {"name": "Escuela Profesional de Psicología", "acronym": "EPPSI"},
            {"name": "Escuela Profesional de Relaciones Industriales", "acronym": "EPRI"},
            {"name": "Escuela Profesional de Ciencias de la Comunicación", "acronym": "EPCC"}
        ]
    }

    for faculty_acronym, schools in schools_by_faculty.items():
        try:
            faculty_obj = Faculty._default_manager.get(acronym=faculty_acronym)
            for school_data in schools:
                ProfessionalSchool._default_manager.update_or_create(
                    acronym=school_data["acronym"],
                    defaults={
                        "name": school_data["name"],
                        "faculty": faculty_obj,
                        "description": f"{school_data['name']} perteneciente a la {faculty_obj.name}."
                    }
                )
        except Faculty.DoesNotExist:
            continue

def rollback_unsa_schools(apps, schema_editor):
    ProfessionalSchool = apps.get_model('institution', 'ProfessionalSchool')
    ProfessionalSchool._default_manager.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_populate_faculties'),
    ]

    operations = [
        migrations.RunPython(populate_unsa_schools, reverse_code=rollback_unsa_schools),
    ]
