# Generated by Django 5.2.17 on 2026-08-15 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_alter_area_managers_alter_faculty_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['-created_at'], 'verbose_name': 'Área', 'verbose_name_plural': 'Áreas'},
        ),
        migrations.AlterModelOptions(
            name='faculty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Facultad', 'verbose_name_plural': 'Facultades'},
        ),
        migrations.AlterModelOptions(
            name='professionalschool',
            options={'ordering': ['-created_at'], 'verbose_name': 'Escuela Profesional', 'verbose_name_plural': 'Escuelas Profesionales'},
        ),
    ]
