# Generated by Django 5.2.16 on 2026-08-06 19:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0012_studentcourseattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], default='DRAFT', max_length=10)),
                ('duration_weeks', models.PositiveSmallIntegerField(default=17, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(52)])),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('foundation', models.TextField(blank=True, default='')),
                ('instructors', models.JSONField(blank=True, default=list)),
                ('competencies', models.JSONField(blank=True, default=list)),
                ('thematic_content', models.JSONField(blank=True, default=list)),
                ('teaching_methods', models.TextField(blank=True, default='')),
                ('teaching_media', models.TextField(blank=True, default='')),
                ('organization_forms', models.TextField(blank=True, default='')),
                ('formative_research', models.TextField(blank=True, default='')),
                ('social_responsibility', models.TextField(blank=True, default='')),
                ('weekly_schedule', models.JSONField(blank=True, default=list)),
                ('evaluation_strategy', models.TextField(blank=True, default='')),
                ('evaluation_schedule', models.JSONField(blank=True, default=list)),
                ('approval_requirements', models.TextField(blank=True, default='')),
                ('bibliography', models.JSONField(blank=True, default=list)),
                ('source_document_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.courseoffering')),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='syllabi', to='academics.curriculumcourse')),
            ],
            options={
                'verbose_name': 'sílabo',
                'verbose_name_plural': 'sílabos',
                'ordering': ['-course_offering__academic_period__year', 'course_offering__academic_period__term', 'course_offering__course__code'],
                'constraints': [models.UniqueConstraint(fields=('course_offering', 'curriculum_course'), name='unique_syllabus_per_offering_curriculum')],
            },
        ),
    ]
