# Generated by Django 5.2.16 on 2026-08-06 07:22

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0011_course_offering_identity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('section_type', models.CharField(choices=[('THEORY', 'Teoría'), ('LABORATORY', 'Laboratorio')], max_length=10)),
                ('group_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='academics.courseoffering')),
            ],
            options={
                'verbose_name': 'sección de horario',
                'verbose_name_plural': 'secciones de horario',
                'ordering': ['course_offering_id', 'section_type', 'group_code'],
            },
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado'), (7, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='scheduling.coursesection')),
            ],
            options={
                'verbose_name': 'reunión de clase',
                'verbose_name_plural': 'reuniones de clase',
                'ordering': ['day_of_week', 'start_time', 'end_time'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_scenarios', to='academics.academicperiod')),
                ('curriculum_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule_scenarios', to='academics.curriculumplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_scenarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'escenario de horario',
                'verbose_name_plural': 'escenarios de horario',
                'ordering': ['-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_offering', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_selections', to='academics.courseoffering')),
                ('curriculum_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_selections', to='academics.curriculumcourse')),
                ('laboratory_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='laboratory_scenario_selections', to='scheduling.coursesection')),
                ('theory_section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='theory_scenario_selections', to='scheduling.coursesection')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='scheduling.schedulescenario')),
            ],
            options={
                'verbose_name': 'selección de escenario',
                'verbose_name_plural': 'selecciones de escenario',
                'ordering': ['curriculum_course__cycle', 'course_offering__course__code'],
            },
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('group_code'), models.F('course_offering'), models.F('section_type'), name='unique_section_group_per_offering_type_ci'),
        ),
        migrations.AddConstraint(
            model_name='coursesection',
            constraint=models.CheckConstraint(condition=models.Q(('group_code', ''), _negated=True), name='course_section_group_code_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='classmeeting',
            constraint=models.UniqueConstraint(fields=('section', 'day_of_week', 'start_time', 'end_time'), name='unique_class_meeting_time_per_section'),
        ),
        migrations.AddConstraint(
            model_name='classmeeting',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='class_meeting_start_before_end'),
        ),
        migrations.AddConstraint(
            model_name='schedulescenario',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('user'), models.F('academic_period'), models.F('curriculum_plan'), name='unique_schedule_scenario_name_ci'),
        ),
        migrations.AddConstraint(
            model_name='schedulescenario',
            constraint=models.CheckConstraint(condition=models.Q(('name', ''), _negated=True), name='schedule_scenario_name_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='scenarioselection',
            constraint=models.UniqueConstraint(fields=('scenario', 'course_offering'), name='unique_offering_per_schedule_scenario'),
        ),
    ]
